model:
  class_name: model.LVSM_scene_encoder_decoder_wEditor_obj-with-light.LatentSceneEditor

  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9

  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6

  env_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9

  decoder_head:
    type: mlp
    mlp:
      use_sigmoid: true

  transformer:
    d: 768
    d_head: 64
    encoder_n_layer: 12
    decoder_n_layer: 12
    special_init: true
    depth_init: true
    use_qk_norm: true
    n_latent_vectors: 3072
    editor:
      n_layer: 12
      init_scale: 0.1
      init_from_decoder: false
    freeze_reconstructor_renderer: true

training:
  amp_dtype: bf16
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 8
  beta1: 0.9
  beta2: 0.95
  allowed_gradnorm_factor: 5
  center_crop: true
  scene_scale_factor: 1.35
  LVSM_checkpoint_dir: ckpt/realworld_exps_obj-with-light
  checkpoint_dir: ckpt/LVSM_scene_encoder_decoder_wEditor_obj-with-light_crosssplit
  checkpoint_every: 2000

  dataset_name: data.dataset_scene_obj-with-light.Dataset
  dataset_path: data_samples/processed_obj_with_light_objaverse_like_testenv_venv_fix_orient_lr3/test/full_list.txt
  context_dataset_path: data_samples/processed_obj_with_light_objaverse_like_testenv_venv_fix_orient_lr3/train/full_list.txt
  cross_split_relight: true
  cross_split_fix_envmap_size: true
  cross_split_envmap_h: 256
  cross_split_envmap_w: 512
  editor_condition_source: target

  relight_signals: [envmap]
  use_relit_images: true
  single_env_map: true
  target_has_input: false

  grad_accum_steps: 1
  grad_checkpoint_every: 1
  grad_clip_norm: 1.0
  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.5
  reset_training_state: true

  lr: 0.0001
  train_steps: 100000
  num_input_views: 16
  num_target_views: 1
  num_views: 17
  num_threads: 4
  num_workers: 2
  prefetch_factor: 32
  print_every: 20
  square_crop: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  vis_every: 1000
  wandb_exp_name: LVSM_edit_obj-with-light_crosssplit
  wandb_log_every: 50
  wandb_project: LVSM
  warmup: 1500
  weight_decay: 0.05

inference:
  if_inference: false
  same_pose: false
  compute_metrics: false
  render_video: false
